# -*- coding: utf-8 -*-
"""sql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3R7FPRh4PEabf94IdNA__nVPcLb0TPL
"""

from datetime import date, timedelta
import random

# Préparer les 200 entrées INSERT
regions = ['Casa', 'Rabat', 'Fès', 'Tanger', 'Oujda', 'Agadir', 'Al Hoceima']
customers = []
base_number = 60000000

for i in range(1, 201):
    phone_number = f"+2126{base_number + i:07d}"
    name = f"Client {i}"
    sub_type = 'postpaid'
    plan_id = 'RP1' if i % 2 == 0 else 'RP2'
    activation_date = date.today() - timedelta(days=i)
    status = 'active'
    region = random.choice(regions)

    customers.append(
        f"('{phone_number}', '{name}', '{sub_type}', '{plan_id}', '{activation_date}', '{status}', '{region}')"
    )

# Construire la requête SQL complète
insert_statement = "INSERT INTO customers (customer_id, customer_name, subscription_type, rate_plan_id, activation_date, status, region) VALUES\n"
insert_statement += ",\n".join(customers) + ";"

# Sauvegarder dans un fichier texte
file_path = "insert_customers.sql"
with open(file_path, "w") as file:
    file.write(insert_statement)

file_path  # Retourner le chemin du fichier créé pour téléchargement.

# Générer les 200 numéros de téléphone
base_number = 60000000
phone_numbers = [f"+2126{base_number + i:07d}" for i in range(1, 201)]

# Sauvegarder dans un fichier texte
file_path = "liste_numeros_telephones.txt"
with open(file_path, "w") as file:
    file.write("\n".join(phone_numbers))

file_path

